version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres_db:/var/lib/postgresql/data # Persist the data.
      - ./schema:/docker-entrypoint-initdb.d/ # Make sure all schemas are set up at boot.
volumes:
  postgres_db:
